dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: 1GHZASX4cuRfuWVuZoN7sylSgSljZqyvsoOdnP1hPZyRsMXKindjihHUztF2OLbU9TLEvM/V8luv6cLqaG1Vgc6RCOuO94QSxik/QhnR3ZDSSa14MGOCfYe+vGZFtUMSeinBb13TjTW5ZoaIXjcXZiym6SkqXpIOL0Qcz6MwcTTb+G/spKQn5xDhcCQPC1xz5a68DzOHrsEd6GO/ZJScaEJhPnCTmVJ6pVUQ5H7AweMLcYJhSYBEWiWc7kgAz5Wg3PJeHyHR2jtD0UpB8p+cD6lvemiafQL3FsmJqNSIoUwWfsA5MAs2Op/Dex5Kpldnfxlp2Hf7xCmddPiy/PSxL5D8VTnCzgrR9cPq57YOifNh/R5Yb5hH0Fndxq5rvVjc3NssPTt9flqydA5XCH6a2BdpJG1h/n5+Ko0ClhRoaXmN2T2Xk22VFqkSeCSoEQGH6DGZpVhAPSlXDl49z6BNMgwoJcthRel5vBwDStsfrRrWbomGf67C+910ZT3YLhzwCkLOsvSGZW4OalsxifFwKS0IPVdxGWKolC5dy3CckBI5n1nSPpOdajnKAPMfKMd/QTIVNTbknxFt2DAPjZxa6+4l4f8/RIHAfEGydgfeAZMaXrDyBY7k+abdEwXkJZwHJMonQmQKqOkUw9RF71J0VEkTtHASZ3z/xk8n+wXaGc4=
