dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: iVrIMAfVmqibroTMGsQzFpjtmiwn03IV+hnjw9eTreeAelotGh8Lt9DluOIIFgBN9m6hQFrkjrGFSxTC/4XbYo0T9r8pS3IqdqEysVi5TT7G2wGBqssayzmHUeEF3ToWQpjigJufO6Sd+y6wFwsadVzZMj6eFQCeFl+36UgjAs2VmVwr7VdxItxl4sGECCk7C40Nvu6u5Xp1LxSE6NbeVNQcTdyM1iXfnmWJUUquveS+1HIVUuDpwITalMEcMYYbIZaTrZwSpjcqPfogGH1yNRaj5ERuQ82ywqQKO6kAPGOM2aE3xrrvkvjzE/PTp93UGzl8L6tsw+b6FHEsCVD5p9WzluZJ8M/UBpVcvhYfa77Le21uw3bka+IlHuyVrisI/qojtw6JqJgFrmGbdoGo64fxyAgKVHrFCspB0p27nS0hqe6dO4SIeIxIHxtaMESmd6xqiV6Lfg4O6ENbJHHH7xwVF9PiLSuKSAZ2aa66vWThpxZ2xCWq4z1nnrWqEozXmiHm7PQ109Yn4c04RqYk8BSTc1109co3FQjSPsN4/bHOlY7tCQZVplmEi7QzHJAdJPwVNYIpFhuUUKlwffiScf99YCJ28XE27Nn84NTnF6ZrVTwsAq/PfxBOpNLEzYjy2cRZLCjTrr5vP6P2xMgPyUFjEjxDnDAGNtAJrKzrmqE=
