dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: Fp7o3HpBrVqIGj+FjOZHeE48yOH07F9bfrvNPIXr2nxE3f+yG9PEYNOG2r6VKL0g90gM0MJp/j4hE5Yw2M1KAPd9RsIpg/hCwuSX30Df1CH8/6Cy1D/V75geNh2+iHeh7XKGjGTf1VOAcUFoe9+nS8wXe1d63Z3VJTUYv2Up3E122OunZn6WYsmoIWKWW0+Xug2kWK4jFWf+jxqYMkTC4K2EBMJIzbeapxFLC9Ys8bki65sAmkIUvBUdGunk/7txFWwVQMgdkJAYlrdioco6OFylvJGO9sAwOR6CrzDfKM0XkSn36XdU0l1TLmjaigYUHR2kpc5fhSwXWSgGHsxrHc5w88x9tXfHrkBfAedUm73/sivFFnMWwa32ZVrU+CtzuIAfKms2PoEhMiGEYOmbUpn/URExH4rX5WV7lFO8uAkW1e5re7iQZmD+A7LG9NYfbsXLvrU4BObRXdvn4WRn6CD+PlEedZuUTw/jW/KPBWATxSLg18DqnLu0eK9hKUlIUcbHlSgcc2Yrmn2hW1z46ZYvrQlkH0T82TqdeY9hf0VefeweN+Oe0mcfpCAk0wMPw36LtN/rkWSmrnjsuSe860guJGYrKmC6Z/aT6UQZjhj6j5Z5GFa6oD+0dAlPJCR7EuKTGWgRU6Fm4wiQvjLaUrV3hveo7o4JdfucnB+wlnQ=
