dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: UUVNao+hh17CYhlovxF4duRY1/z4Pvg67XQyGtSn/5HLN5vegEY8ah/bJ7L4Oxq9n6knqqH2wywFSqy+ZxDCpS/wZtY8SsdOIVq4DkflhQbJ0OeTLjbwB/YtInnGP56+GBT8OQl0o2hvWykwTzTLbSNrWXfpYlo81IrkHo9lxiZDYT3vvYu3gdEOYoo/PolaoRz56mu7pO4UyZJyl/KuocJzrUO9cNYDTCgMMq8e/f7CGG8zp2hgiQl/Pa0SPTl3rUtpAYTY8u9z6rZcAcI6YowFgoVVmSvEwsKaZ5wlu+f2SJEG1vQKcK8ZCYnLfQb/gU3JkBABJBDHhg1rN3uHHV5CR4zkEkQv7nLHup4lAyKN9fWLU85AjhKryrDIGzSlRxwOJsRcf+6tljRmnWs/eY53t7XKjGNNKGQP2h2/3+wTpsoQk7mDsVRP5poMQvB/N0jNqu8OKFwANWSgHwNxYO5hRU13ubjWWz+KVMYr69B0hiEOkEGDv4BNWZUJrRgfhFDvT7r+Egm3WFN0tEdCeHJRqXzIyum/xVGY37mm9k5C/O17+RQXMYD3AW7qTZjG3W4Kx62ZMwgQx7e8yikL0+abDgkfzniM03pQZQ7F4hVqAc+Xvjnk00WZ4ZCR9JoTkMGlRb7MWg2P4z32GP7aRCNdpiHRbsfDN3kgxB3VkDk=
