dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: Z+V35eyWozXW+xqS4IZc6mPpaeDhZWZ6Yxp8YTRRQra/exC+SP131/Nky4Hv30irQIhfB1kyUcKPdmKvae0rBftRW0LXWgw0sZUUMSgshJtwkHjUyrxDdtzpX6dyTWVy8Pn2oGRnlprDZyrQrZG8O2quC8kpri/Y5AhMAgKsv2Ux31aP8EpJedl1dOSS6c7h8xPtroZA8MeQYWlej+7ebiLxgfkU524cmMaPYFeiHzgu2KeHyztFqT13rO+6YdLd84C9puC8oLG5e086RlduODMYnj4wFDoyYMAPWFUTXvz4T4NAFsyzM0CRe10XVkXnkOHkrAONYauAftYV2ckpJio1ga7BCNuC7ODRvdzsTCaSZzOKBclC89RFbvUsLYlF3c5iGzudQsLujdEepcaKP9cNDWdj2UrupS+u3UNDOdkpZMc3ttP/3Dwh8pkgJBJugo7eXQym0rz5HlRd+5H5HrYK8NaaLAdGuZEcq167nZ2soNxO8qNuRKXGd4ktZ4uzxUY84CgIwLmC117NXKArUrNtwpA9T5/rmLid4A8F3k82k4w5W7k3xbtvqMc2kNo9AjlVWDUBfyywRrU7In1PMuZcSp4GWwSnnY2u7hoGw2C6av3v78yVPWh+vqES6uPmuXiXOTyh12Hdw4tg+Roj8lcc3mcnB/owfomxfP6A60s=
