dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh | bash
notifications:
  slack:
    rooms:
      secure: V5r7CtRIIViGUxve4jWXP4bgqMQRy0qUl0xApIsEDihQ2+sFBhDABOJxqR0H/3sSzUEKV2NC3mclORBXTOB6j0/yoCQROpQDqW2nyIxSV0+JY0+Esj8uD3N8ZBqI/5FTzzcIm43DQjjVxIsJPgsdLblDQLoyrf+2SQvSICME6DCvEdj1mXhGyaIzUZp1U0Xj48UxZf3JumD/Y5pf15xC+5TVeGuk5ymhF9n58EYQ/dta1jYMIxYzCzNmdiiW12C75kiXWebJOdzv/3LtO8IOoVn4gBtrfm0J7PQtqdkcmuClz0GkU5fxG6mSD6MNWmFu+1QsT75FZhJLusOEsnLKNitIktXJcH1Xd2NdiJFnNEhtq7hi4ho1aO7vNsCjNEHu+rM4IEkOyNyQE/RiegGUm22T+dIZodt/qzHPzwgdH9tglW2wxs//DcR23UQ2/VpswnJCxWonk3zm4HDl4Tu1Nd+OPi0LapQI5HIb1EmCXDh7V+Y1Y97EEiCwqCNn+2BvELw2W91na64neASqJnn+N08Y36eLysJnsLd3Uch3Nzl4wcqiIhMJQPdmFLJ8hqf3NPUDS/Wcn5qHpxY56nbD+OKOGCTdRuqn+bRR8aqW4mO/jlVB7ukrGM7ijdaDmf5C/IIVK0E+iFCiP3EsFTnOAi6mn7a9G5IGOFJMKdCofWg=
