dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: Eff1ZiiZcYk84YA5UBECtYdqsbwT2wQaK/09I1paopseDJLd+DqZDWQqe9w/PbhIXE8aE2/3MlM9ZYX0dTVBBAzpfPRXMtrKGf12yRDSGuXy/7CRJJK6H9fGZGkeIH0wpr5+Mchz+C6X9eXD1n1csdL14JFGmx1yo+iEyG9nfVWGniNALKx5edzcVOT3E6q6SkWQBh44cDyRG6/E5xbPqume4XV3N28Bmp0k52B2TmnCBeR0W61Cm8XozlZicn+SCMv7Q8TuHtAm0mooda+2JcABccqXNP2ALj9mwH/VQARyeGZN/yT8VB9PbIsBdpBIrnA/uycygDaEylu9vJ3UqslBs/AWQgEFLbUEYoc7BXP9UYQNGVb0wVsZfR8+/7aTN3Sm+7jxvkSXVjtpInBRDDFR+fELzZPU7Jpm8BD/JwVRxEXQP+B/cQve9OnczpOiBxmIw4A6jfr32YP/1fRkzClIn/Sr5/Mi4P+rdDoyCTawQUswqHd49NcB++ZKkTkaGNO6Qxx1MN6dQpfQ0d9wBPv6A4KH3adHKnJU1f/CU4qguibyy40wx7KyEwa8/Z8UQAcOj8TsTgk3VEZ6eXTR2BGowzCIYMGLG2Fc0K9575GxzeHEgZPxGNPn8xsbDT/wkoD3gUwruI1v+ksSd6yEx79j2b+mx/UlVt/tBr8gGqs=
