dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: PFyQjdhaFVgPaFNSzHNMjEELEKjpiqKLjtPd1YxzDSC1Akv1wm5b7l6TzQZs0BpZAxcPO4J8TS7RZnAMmVI96KGJjQsFXYP/v5L7oPhQT4NOUhJiYHid9A1uNXVoCQBR6TDcB0dEN+2SCpLQhcdQtxlOM1ZZHekRO3WcPbqIfAogfIpeglLyJ2Fr1xb/3fNNx6DnE6edxex5d32sGUUp32RLU04woN0hgRXZg84juEitzib4L5A2lvUhlnUVd4dSpSMBg+jjACno+rAAPHYsHqyz6RipWi/E/sletiByf2oU/pNFeMxVH7Cq/8/n5EckEsWQ0vFdpobhZ93B1DoVI9xbxYS2kXPrwerVPZ4Yjh0NoA56RynBVZFRGGlCqoeo7tujHHMynmDClBnlESHz8zWgPL/lsvkCCBRZdSLlQGkJq4ccszE/502EAfHcVplHFqF9r+rDUI6XzlU7JjiIUKIuiMcKBW4j1nM8BXpwAzcqaafr83IyfQc/LFPUOCbeSqYs2vfPsBhzV6CEO69I8urQR7xO2HE0fEokxXDpx4sdMXnf048ub/gCp69z/owwTDaDMvmbaNngs9rkbcDmIc+p4NShk7Foi8hNJk7gnDXxKMA5soc+wZna3T0WhjjLHx/l6fMMspxS2DQi+CUb86mEcKrxHduzBI6EBixVccA=
