dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      - secure: "lLbZzXrd19YULFZcoEJuSY43jcR074LCySArbcOaiGRuIFWkWzqQrnHgqisnigVjDp92Bek8mmXR5hfyR2b6kX8K+o2kBrrTON6MjHUPyj0tdGCOr8x8e52Wq5OhMJM7mxsys4MmJsleMtmdhznB2Y5fZGBMnVqW4hlBieJ8dEsWie4rSt5UmZx0N1LjofYViyAt6WdkG+jzX9H33fW8vEWy0MJJs1sP7+vdkg6TqKR588N9GapxqFpbARVBWbWl0ZW26H+tUCIBwoo2GsuTah4FSkbEwiIhIzRN8hG3TAYKW8LIkZUDGoNK8msvRwA7HeZ7MRQN81ANKiSbQXHPSjGqXOskL6GkPZtwachuxdcmNUBXMrv1+JGxGtlgQfpyGnulYuz4K2FWD8HNhhQ1IpNtS1WF2DD8BunkRTFkJJj35bcaYHfcUbD6aLQpzwmGoAS1VgXZNKBm3M7toMK/aGL4KCHqbyDYANgy8dCiJp3Q1OPTppp4BCKzT/i27A70RfVl9Q3+MOiyGuh64EMa/f6phe2/71BugzwDFvenbLHe4iur8x1p7AyMZ6aLqA1/YqRv9h5/4Q5WRyUL8IS1geLJkC8sgsswccyxHKb48hrPKWTfsCZvEREst0RrkkoxPde8wrIJSu/cdLdJZUSwkONYBQHdBQayJUDlbrQY4HM="
    on_success: always
    on_failure: always
