dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: baYoeAHVg33L6bCzzlII7vkmH2ul3LKTWfdwAmx/r4BRUUxBy4Q7L/+Ul+TV/uZPx3q89jbQxDG47O5HbfmBpqcGsOXOPQ+rNfO93sRvvGON9wTKGoQ1/jsiVI/tNHhBezRSv71UiohLqNHut6rszyUQtooLTbHbKsiIsV3scClmPVh0549GAtXY80AigQWt+g3lPue3rwPMwkZ1aWQw7N2SooMjqpARivTWY0Y5zRgy23bw08FH5bRpabJYh77b8e67ESnI/pd7RwMNP2ITrI7WumSgWhWsJ2ea0L9zkmJwV7EIi851yrPt9nAi5gZrkqSW6cWatyqjm0AVDoN7jzt3Z8i25z3Agb6lZ5AWSGUi78D7Y04mVgocq4vgdy5eXkfAndYHyqUJISHXZks9vdMny218Bietn4WUzX4MKy5lyTUytdH8X0tDxT8Y4AN5Vpd65rG+jZae/DBoV9q9+3gGtaLlIxDqa2K3t4hRHKzkzyYyFqYzZ07x39PbeNUNMCAw3f6mYvss/1/7gaumRy7+VzrrdcP06Yjqm1gUU7NLIRbU+y81cEOIi/reGqs0cdbJtVa+vf/gATWz6CcRH5dQgwOEop1kYdfFnHgzzJpCazHBOzvoIZ/R7SNBwlHf7sdDAVN23nLyDmkxHU4b8MAk7NZKmTbxX4VLv6sjg6s=
