dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: KyDDTchBkUkI/XI1o9vnpWDwSVt0FdDK2DM14GMdN0GHCFitgC/dXMXTLaRiY6FC7G9VOxQprY2LJfw30S4WeVhJaW9jXzrz5Ib7zeqQUcSiwPDvgzySBgQKoURWjj9xoZ6SNa+W9G8V1aAJdcdlPrnfYEU2b542yee5ZF5WDsJOpr2stbOasVVeZshCeQzVyhzK+ZDIEekGbUHYRWHxgdWt3Z47d9lJ3LvQhbDoa9MwcJ5GoEa+qfWYEZj3oc2x2+aAG66eqqFG/I3F5D+CZXhPouEflSFqLG2j/7JZHebLyrsXEXFX/M6PfR2TT6iiS08zElgOiV1R63fHuTuSTDT6FHHQjciPUvX/F8MckstlsGAeWCc+jZo9IdA6CFYmfYExZt/NXxQgtWQPQYIW2pgxmKFg/OfmDyfpqzddjeKGSWQku85o84v09dJnOn+/L1BCVQnGW43oNgwPGN1fptj3KTcvyColauXYV2E0PMcoFjapRH6p2zQw4da4jlYCbpmT7JSJ3puQJHBXaPpVjJ/jjUU1ewNdSpZJen5Tes2ZGuIxRelfHkEY2gJLI/hkqpMpqe5BdepZ1+wE8661aOnI4iPd7LMtUT/0jYtE0owWXBTJyexlcDMTKloYvi9kJYt3MKhSfXUj6mVmCFuQKbMQvsIEc/+xEPJGYc8f+uI=
