---
- name: Configure application
  hosts: appserver
  become: true
  roles:
    - app
    - role: jdauphant.nginx
      nginx_sites:
        puma.local:
          - listen 80
          - location / { proxy_pass http://127.0.0.1:9292; proxy_http_version 1.1; }

